# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Executa o código
      run: |
        docker ps  
        docker compose down
        docker container stop $(docker image ls -aq)
        docker ps  
        docker image ls
        docker rmi $(docker images 'docusaurus-1r1sjc-docusaurus' -a -q)
        docker image ls
        docker compose up -d
